# Generated by Django 4.1.6 on 2023-02-27 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_msg', models.TextField(max_length=300)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 2, 27, 10, 1, 14, 651619, tzinfo=datetime.timezone.utc), null=True)),
                ('visibility_to_close_friends', models.BooleanField(null=True)),
            ],
        ),
    ]
